@echo off
echo Running API tests...
echo Switching to backend directory...
cd backend
echo Triggering API tests...
call npm run test:api

echo API tests completed.
echo Switching back to root directory...
cd ..

echo Running E2E tests...
echo Switching to frontend directory...
cd frontend
echo Installing Playwright...
call npx playwright install
echo Triggering E2E tests...
call npm run test

echo E2E tests completed.
echo Switching back to root directory...
cd ..